// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgF5XN35EVooeomVp6GbQIiokkR6gRf5I',
    appId: '1:465789645018:web:f7026ff98b007fab35f5e3',
    messagingSenderId: '465789645018',
    projectId: 'gestiontaches-cc7e7',
    authDomain: 'gestiontaches-cc7e7.firebaseapp.com',
    storageBucket: 'gestiontaches-cc7e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFJSZj3WRt-Wp6yS7C_e678Y3gKLh46o',
    appId: '1:465789645018:android:93086aad41aa221535f5e3',
    messagingSenderId: '465789645018',
    projectId: 'gestiontaches-cc7e7',
    storageBucket: 'gestiontaches-cc7e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kggz3jgkmMOA0QV8weTqjeJVKyj8LY8',
    appId: '1:465789645018:ios:9d13d5075f79c28535f5e3',
    messagingSenderId: '465789645018',
    projectId: 'gestiontaches-cc7e7',
    storageBucket: 'gestiontaches-cc7e7.appspot.com',
    iosBundleId: 'com.example.gestionTaches',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kggz3jgkmMOA0QV8weTqjeJVKyj8LY8',
    appId: '1:465789645018:ios:1709dd34543bb01835f5e3',
    messagingSenderId: '465789645018',
    projectId: 'gestiontaches-cc7e7',
    storageBucket: 'gestiontaches-cc7e7.appspot.com',
    iosBundleId: 'com.example.gestionTaches.RunnerTests',
  );
}
